---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: 4ms.rotatingclockdivider
aspect:
  color: white
diy: true
events:
  - date: 2017-12-05
    kind: buy
    source: kit (thonk)
    destination: storage
    price: 110

  - date: 2017-12-16
    kind: build
    build_operator: schematicwizard
    build_duration: 2d
    build_result: failure
    build_notes: |
      Operator failed to solder a resistor array on the right side of the pcb
      and had to unsolder a the component, breaking it and damaging the pcb.
      After buying a new resistor array and trying soldering it properly,
      another mistake was made. The module ended up partially working. There is
      a remaining issue with the output voltage levels, making it unusable.
      Output levels are not sufficient for a standard trigger/gate signal and
      most envelope generators or samplers react poorly to it

  - date: 2017-12-16
    kind: failure
    failure_notes: |
      See build
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
