---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: alrightdevices.chronoblob2
aspect:
  color: white
events:
  - date: 2022-10-26
    kind: buy
    source: operator (Marc Debroey - SEBASTOPOLmusic (BE))
    destination: ELM-0004
    price: 280
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
