---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: befaco.stmix
aspect:
  color: black
diy: true
events:
  - date: 2023-03-07
    kind: buy
    source: retail (befaco)
    destination: storage
    price: 84

  - date: 2023-03-11
    kind: build
    build_operator: schematicwizard
    build_duration: 1d
    build_result: success

  - date: 2023-03-11
    kind: move
    source: storage
    destination: ELM-0004
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
