---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: bela.gliss
aspect:
  color: black
events:
  - date: 2024-02-10
    kind: buy
    source: retail (thomann)
    destination: storage
    price: 149

  - date: 2024-03-30
    kind: move
    source: storage
    destination: ELM-0002
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
