---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: mutableinstruments.links
aspect:
  color: white
events:
  - date: 2017-04-03
    kind: buy
    source: retail (thomann)
    destination: ELM-0002
    price: 68

  - date: 2024-12-06
    kind: move
    source: ELM-0002
    destination: storage
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
