---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: mutableinstruments.veils2016
aspect:
  color: white
events:
  - date: 2017-04-03
    kind: buy
    source: retail (thomann)
    destination: ELM-0002
    price: 175

  - date: 2021-07-24
    kind: move
    source: ELM-0002
    destination: storage

  - date: 2021-08-10
    kind: lend-out
    source: storage
    destination: operator (anee molly)

  - date: 2022-06-26
    kind: lend-in
    source: operator (anee molly)
    destination: ELM-0002
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
