---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: rossemelectromusic.trident
aspect:
  color: white
events:
  - date: 2022-11-26
    kind: buy
    source: operator (Xavier Reuss)
    destination: ELM-0002
    price: 500
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
