---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: xorelectronics.nerdseqmorecv16
aspect:
  color: black
events:
  - date: 2024-10-29
    kind: buy
    source: retail (musicstore)
    destination: ELM-0002
    price: 170
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/module.json
