# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/grid/sector.json
apiVersion: billofmaterials.art/v1
kind: grid/sector
metadata:
  name: Complex
  shortName: cpx
  company: Bill of Materials
  kind: agency
  altNames:
    - Central Agency
    - Millenium Falcon Lair
    - mkb
  location:
    address: |
      "[redacted]"
    city: "[redacted]"
    region: Ile-de-France
    country: France
events:
  # - kind: build
  #   date: 2020-??
  - kind: buy
    date: 2026-10-07
    owner: OP-0022
    price: 339000
  - kind: activityStart
    date: 2026-10-07
  # - kind: activityEnd
  #   date: 2026-10-07
