---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: expertsleepers.es8
aspect:
  color: black
events:
  - date: 2020-11-11
    kind: buy
    source: retail (signalsound)
    destination: ELM-0002
    price: 462
