---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: happynerding.fxaid
aspect:
  color: black
events:
  - date: 2021-12-01
    kind: trade-in
    source: operator (Kevin Paul Cachay (FR))
    destination: ELM-0002
    trade_with:
      - happynerding.fxaid-wht # white

  - date: 2022-06-03
    kind: move
    source: ELM-0002
    destination: ELM-0004
