---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: intellijel.quadrax
aspect:
  color: white
events:
  - date: 2021-07-24
    kind: buy
    source: retail (modularsquare)
    destination: ELM-0002
    price: 358
