---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
modulespec: mutableinstruments.links
aspect:
  color: white
events:
  - date: 2017-04-03
    kind: buy
    source: retail (thomann)
    destination: ELM-0002
