---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
name: Hexpander
company: Befaco
description: |
  Hexmix expander with 3 aux sends, PFL, individual outs per channel and master
  balanced out
url: https://modulargrid.net/e/befaco-hexpander
tags:
  - expander
  - external
  - mixer
  - utility
  - dual/stereo
current:
  12pos: 137
  12neg: 64
  5pos: 0
  power: daisy
dimensions:
  width: 28
  height: 3
  depth: 27
