---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
name: René 2
company: Make Noise
description: |
  A sophisticated Cartesian sequencer designed to generate complex sequences of
  control voltages with intuitive control and visual feedback, ideal for
  performance and live tweaking.
url: https://modulargrid.net/e/make-noise-rene-mk2
tags:
  - controller
  - cv modulation
  - logic
  - quantizer
  - sequencer
current:
  12pos: 235
  12neg: 0
  5pos: 0
dimensions:
  width: 34
  height: 3
  depth: 24
