---
apiVersion: billofmaterials.art/v1
kind: eurorack/module
name: OpticShifter
company: TEIA Synthesizers
description: |
  20 pole Phase Shifter
url: https://modulargrid.net/e/teia-opticshifter
tags:
  - distortion
  - drum
  - phase shifter
current:
  12pos: 110
  12neg: 100
  5pos: 0
dimensions:
  width: 12
  height: 3
  depth: 42
