---
apiVersion: billofmaterials.art/v1
kind: eurorack/modulespec
name: Ciao!
company: Bastl Instruments
description: |
  Quad line output & headphones amp
url: https://modulargrid.net/e/bastl-instruments-ciao
tags:
  - external
  - mixer
  - utility
power:
  12pos: 40
  12neg: 40
  5pos: 0
dimensions:
  width: 5
  height: 3
  depth: 55
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/modulespec.json
