---
apiVersion: billofmaterials.art/v1
kind: eurorack/modulespec
name: A-130-8
company: Doepfer
description: |
  Octal Linear VCA / Mixer
url: https://modulargrid.net/e/doepfer-a-130-8
tags:
  - vca
  - quad
  - mixer
power:
  12pos: 50
  12neg: 50
  5pos: 0
dimensions:
  width: 6
  height: 3
  depth: 40
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/modulespec.json
