---
apiVersion: billofmaterials.art/v1
kind: eurorack/modulespec
name: OpticShifter
company: TEIA Synthesizers
description: |
  20 pole Phase Shifter
url: https://modulargrid.net/e/teia-opticshifter
tags:
  - distortion
  - drum
  - phase shifter
power:
  12pos: 110
  12neg: 100
  5pos: 0
dimensions:
  width: 12
  height: 3
  depth: 42
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/modulespec.json
