---
apiVersion: billofmaterials.art/v1
kind: eurorack/modulespec
name: VCRadio
company: X Audio Systems
description: |
  A radio receiver module designed for Eurorack systems, capable of picking up
  AM and FM signals, providing unique sound sources and modulation capabilities.
url: https://modulargrid.net/e/x-audio-systems-vcradio
tags:
  - noise
  - cv modulation
  - dual/stereo
  - random
power:
  12pos: 55
  12neg: 45
  5pos: 0
dimensions:
  width: 8
  height: 3
  depth: 25
# yaml-language-server: $schema=../../../schemas/billofmaterials.art/v1/eurorack/modulespec.json
